services:
    backend:
        build:
            context: backend
            target: builder
        # flask requires SIGINT to stop gracefully
        # (default stop signal from Compose is SIGTERM)
        stop_signal: SIGINT
        ports:
            - '$BACKEND_PORT:5000'

    frontend:
        build:
            target: build-stage
            context: frontend
        ports:
            - $FRONTEND_PORT:3000
            
    stripe-cli:
        image: stripe/stripe-cli
        container_name: stripe-cli
        network_mode: host
        command: "listen --api-key ${STRIPE_API_KEY} --forward-to localhost:${BACKEND_PORT}/webhook"
