services:
  backend: 
    build:
      context: backend
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '5001:5000'
      
  frontend:
    build:
      target: build-stage
      context: cli
    ports:
    - 3000:3000
      
