"""updated-user

Revision ID: 0cc992202893
Revises: dd9c141cbe11
Create Date: 2024-03-27 18:16:26.117171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc992202893'
down_revision = 'dd9c141cbe11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=32), nullable=True))
        batch_op.drop_column('sex')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
