"""stripe-fields

Revision ID: 9ff424bdef3f
Revises: ea7444a96fa9
Create Date: 2024-05-01 16:49:24.173879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff424bdef3f'
down_revision = 'ea7444a96fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_product', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('stripe_price', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_plan', schema=None) as batch_op:
        batch_op.drop_column('stripe_price')
        batch_op.drop_column('stripe_product')

    # ### end Alembic commands ###
