"""removed-salt

Revision ID: b0d3f46b8918
Revises: ffeb86b95fbd
Create Date: 2024-03-26 19:13:27.060076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d3f46b8918'
down_revision = 'ffeb86b95fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.drop_column('salt')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(length=60), nullable=True))

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(length=60), nullable=True))

    # ### end Alembic commands ###
