"""initial migration

Revision ID: ba92c7150724
Revises: 
Create Date: 2024-02-19 14:15:22.934460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba92c7150724'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membership_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('payment_regularity', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('salt', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('salt', sa.String(length=60), nullable=True),
    sa.Column('profile_picture', sa.LargeBinary(), nullable=True),
    sa.Column('sex', sa.String(length=32), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('fk_membership', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_membership'], ['membership_plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('friend',
    sa.Column('fk_user_1', sa.Integer(), nullable=False),
    sa.Column('fk_user_2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_user_1'], ['user.id'], ),
    sa.ForeignKeyConstraint(['fk_user_2'], ['user.id'], ),
    sa.PrimaryKeyConstraint('fk_user_1', 'fk_user_2')
    )
    op.create_table('friend_request',
    sa.Column('fk_from_user', sa.Integer(), nullable=False),
    sa.Column('fk_to_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_from_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['fk_to_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('fk_from_user', 'fk_to_user')
    )
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('exercise_type', sa.String(length=64), nullable=True),
    sa.Column('fk_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'fk_user')
    )
    op.create_table('user_in_group',
    sa.Column('fk_user', sa.Integer(), nullable=False),
    sa.Column('fk_group', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_group'], ['group.id'], ),
    sa.ForeignKeyConstraint(['fk_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('fk_user', 'fk_group')
    )
    op.create_table('route_in_group',
    sa.Column('fk_route', sa.Integer(), nullable=False),
    sa.Column('fk_group', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_group'], ['group.id'], ),
    sa.ForeignKeyConstraint(['fk_route'], ['route.id'], ),
    sa.PrimaryKeyConstraint('fk_route', 'fk_group')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_in_group')
    op.drop_table('user_in_group')
    op.drop_table('route')
    op.drop_table('friend_request')
    op.drop_table('friend')
    op.drop_table('user')
    op.drop_table('owner')
    op.drop_table('membership_plan')
    op.drop_table('group')
    # ### end Alembic commands ###
