"""updated-user

Revision ID: dd9c141cbe11
Revises: c77dea4e071a
Create Date: 2024-03-27 18:15:39.731341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9c141cbe11'
down_revision = 'c77dea4e071a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.DATETIME(), nullable=True))
        batch_op.drop_column('age')

    # ### end Alembic commands ###
