"""empty message

Revision ID: ea7444a96fa9
Revises: 2583f9b35003
Create Date: 2024-05-01 13:11:38.144613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7444a96fa9'
down_revision = '2583f9b35003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
